<?php
/**
 * Deletes any temp files that are past the limit
 *
 * @author Mark Guinn <mark@adaircreative.com>
 * @date 10.30.2013
 * @package shop_downloads
 * @subpackage tasks
 */
class CleanupDownloadableTempFilesTask extends BuildTask
{
	protected $title = 'Downloadable Products: Clean Up Temporary Files';
	protected $description = 'Deletes all zip archives and temporary files generated by the downloadable products module older than the number of hours set in the configuration.';

	public function run($request) {
		$files = DownloadTempFile::get();
		$num = 0;

		foreach ($files as $file) {
			if ($file->isOutdated()) {
				$file->delete();
				$num++;
			}
		}

		echo "$num files were deleted.";
	}
}