<?php
/**
 * Deletes all temp files from downloadable orders.
 *
 * @author Mark Guinn <mark@adaircreative.com>
 * @date 10.30.2013
 * @package shop_downloadable
 * @subpackage tasks
 */
class DeleteDownloadableTempFilesTask extends BuildTask
{
	protected $title = 'Downloadable Products: Delete All Temporary Files';
	protected $description = 'Deletes all zip archives and temporary files generated by the downloadable products module.';

	public function run($request) {
		$files = DownloadTempFile::get();
		$num = 0;

		foreach ($files as $file) {
			$file->delete();
			$num++;
		}

		echo "$num files were deleted.";
	}
}